name: Build and deploy Hugo project to GitHub pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the site
        uses: joohoi/hugo-deploy@master
        env:
          DEPLOY_REPO: who1s/who1s.github.io
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_TOKEN }}
          DEPLOY_USER: who1s
